### ISSUE TITLE
ValueError: 'message' longer than 3 bytes but does not start with 0xF0.

### ISSUE THREAD

**Issue by thijstriemstra** [raspy135/serialmidi#5]
```
$ python serialmidi.py --serial_name=/dev/ttyUSB0 --midi_in_name="Midi Through:Midi Through Port-0 14:0" --midi_out_name="Midi Through:Midi Through Port-0 14:0"
INFO:root:IN : 'Midi Through:Midi Through Port-0 14:0'
INFO:root:OUT : 'Midi Through:Midi Through Port-0 14:0'
INFO:root:Hit ctrl-c to exit
Exception in thread Thread-3:
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/threading.py", line 926, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.7/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "serialmidi.py", line 158, in midi_watcher
    midiout.send_message(message)
  File "src/_rtmidi.pyx", line 1103, in rtmidi._rtmidi.MidiOut.send_message
ValueError: 'message' longer than 3 bytes but does not start with 0xF0.
```

using python 3.7 on Ubuntu 20.04

any idea?

**Comment by raspy135** [comment]
Hi, I have never tested it in Linux. 
I will try it when I have time.
Is there any alternative software on Linux?

**Comment by raspy135** [comment]
The error message says the MIDI message is not valid. 
Try --debug option, it will dump MIDI messages. If it prints random MIDI messages, probably serial setting is not correct.
Is the baud rate correct? One of common error is setting incorrect baud rate.

**Comment by thijstriemstra** [comment]
thanks, the baudrate was indeed incorrect.
